name: Docker CI

on:
  push:
    branches: [ main, feat/docker ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Docker image
      run: docker build -t my-docker-app .

    - name: Run container and test it
      run: |
        docker run -d -p 5000:5000 my-docker-app
        sleep 5
        curl -f http://localhost:5000 || exit 1
